

const EventEmitter = require('events')
const emitter = new EventEmitter()
let logins = 0
let logouts = 0
let purchases = 0
let updates = 0
emitter.on('login', () => {
    console.log('user Login')
    logins = logins + 1
})
emitter.on('logout', () => {
    console.log('user Logout')
    logouts = logouts + 1
})
emitter.on('purchase', () => {
    console.log('user Nike Shoe Purchased')
    purchases = purchases + 1
})
emitter.on('profileUpdate', () => {
    console.log('user Updated a profile')
    updates = updates + 1
})

emitter.on('summary', () => {
    console.log({
        login: logins,
        purchase: purchases,
        logout: logouts,
        update: updates
    })
})


emitter.emit('login')
emitter.emit('login')
emitter.emit('login')
emitter.emit('login')
emitter.emit('login')
emitter.emit('login')
emitter.emit('login')
emitter.emit('login')
emitter.emit('login')
emitter.emit('login')
emitter.emit('login')
emitter.emit('login')
emitter.emit('login')
emitter.emit('login')
emitter.emit('login')
emitter.emit('login')
emitter.emit('login')
emitter.emit('login')
emitter.emit('login')
emitter.emit('login')
emitter.emit('login')
emitter.emit('login')
emitter.emit('login')
emitter.emit('login')
emitter.emit('login')
emitter.emit('logout')
emitter.emit('logout')
emitter.emit('purchase')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('profileUpdate')
emitter.emit('summary')